on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  CI:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level:
          - 29
    steps:
      - uses: actions/checkout@v3
      - name: JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          channel: canary
          profile: "Nexus S"
          api-level: '${{ matrix.api-level }}'
          force-avd-creation: false
          emulator-options: >-
            -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
            -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
